### ISSUE TITLE
Unsupported URL

### ISSUE THREAD

**Issue by iqsalah** [debakarr/kodekloud-downloader#31]
download] /content/drive/MyDrive/KodeKloud/Linux Foundation Certified System Administrator LFCS/4 - User and Group Management 14 Topics/10 - Manage access to the root account 0252.mkv has already been downloaded
ERROR: Unsupported URL: https://kodekloud.com/topic/configure-the-system-to-use-ldap-user-and-group-accounts%e2%9c%a8/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 1702, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://kodekloud.com/topic/configure-the-system-to-use-ldap-user-and-group-accounts%e2%9c%a8/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/kodekloud", line 8, in <module>
    sys.exit(kodekloud())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/kodekloud_downloader/cli.py", line 73, in dl
    download_course(
  File "/usr/local/lib/python3.10/dist-packages/kodekloud_downloader/main.py", line 69, in download_course
    current_video_url = get_video_info(lesson.url, cookie=cookie).get("url")
  File "/usr/local/lib/python3.10/dist-packages/kodekloud_downloader/helpers.py", line 155, in get_video_info
    info = ydl.extract_info(url, download=False)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 1556, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 1585, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 1045, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 984, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: Unsupported URL: https://kodekloud.com/topic/configure-the-system-to-use-ldap-user-and-group-accounts%e2%9c%a8/

**Comment by iqsalah** [comment]
HOW TO SKIP THIS VIDEO ?
WHAT SHOULD I WRITE IN THE CODE ?

**Comment by iqsalah** [comment]
HOW TO SKIP THIS VIDEO ?
WHAT SHOULD I WRITE IN THE CODE ?

**Comment by iqsalah** [comment]
I mean what i write to exclude that link cuz it's empty link, it doesnt contain any file.

**Comment by debakarr** [comment]
Closing stale issues.
Please raise a new issue if you still see the problem :)
