### ISSUE TITLE
Quiz download stop with error

### ISSUE THREAD

**Issue by Tanis74** [debakarr/kodekloud-downloader#36]
`Fetching Quiz 44 - Lab MCQ IAC and Terraform Basics
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\kodekloud.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\kodekloud_downloader\cli.py", line 101, in dl_quiz
    download_quiz(output_dir, sep)
  File "C:\Program Files\Python310\lib\site-packages\kodekloud_downloader\main.py", line 59, in download_quiz
    Path(output_file).write_text(markdown_text)
  File "C:\Program Files\Python310\lib\pathlib.py", line 1155, in write_text
    return f.write(data)
  File "C:\Program Files\Python310\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u200b' in position 9904: character maps to <undefined>`

**Comment by MM-Ty** [comment]
facing same issue

**Comment by debakarr** [comment]
I have the full material scraped here: https://gist.github.com/debakarr/4edd7dddd5278ec7b97603f54a6771da

**Comment by debakarr** [comment]
Closing stale issues.
Please raise a new issue if you still see the problem :)
