### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by Vasanth2904** [debakarr/kodekloud-downloader#41]
024-03-15 18:36:21,022 - INFO - Parsing url: https://kodekloud.com/topic/course-introduction-16/
[generic] Extracting URL: https://kodekloud.com/topic/course-introduction-16/
[generic] course-introduction-16: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] course-introduction-16: Extracting information
[vimeo] Extracting URL: https://player.vimeo.com/video/679026400?h=caa57dd404&dnt=1&app_id=122963&controls=1&autoplay=1&m...oduction-16%2F%22%7D
[vimeo] 679026400: Downloading webpage
[vimeo] 679026400: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 679026400: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 679026400: Downloading fastly_skyfire m3u8 information
[vimeo] 679026400: Downloading fastly_skyfire m3u8 information
[vimeo] 679026400: Downloading akfire_interconnect_quic MPD information
[vimeo] 679026400: Downloading akfire_interconnect_quic MPD information
[vimeo] 679026400: Downloading fastly_skyfire MPD information
[vimeo] 679026400: Downloading fastly_skyfire MPD information
[info] 679026400: Downloading subtitles: en
[info] 679026400: Downloading 1 format(s): dash-fastly_skyfire_sep-video-0f8dfd99+dash-fastly_skyfire_sep-audio-fce216e6
[info] Writing video subtitles to: KodeKloud\Jenkins\1 - Introduction\1 - Course Introduction 0235.en.vtt
[download] Unable to open file: [Errno 13] Permission denied: 'KodeKloud\\Jenkins\\1 - Introduction\\1 - Course Introduction 0235.en.vtt.part'. Retrying (1/3)...
[download] Unable to open file: [Errno 13] Permission denied: 'KodeKloud\\Jenkins\\1 - Introduction\\1 - Course Introduction 0235.en.vtt.part'. Retrying (2/3)...
[download] Unable to open file: [Errno 13] Permission denied: 'KodeKloud\\Jenkins\\1 - Introduction\\1 - Course Introduction 0235.en.vtt.part'. Retrying (3/3)...
ERROR: unable to open for writing: [Errno 13] Permission denied: 'KodeKloud\\Jenkins\\1 - Introduction\\1 - Course Introduction 0235.en.vtt.part'
ERROR: Unable to download video subtitles for 'en': ERROR: unable to open for writing: [Errno 13] Permission denied: 'KodeKloud\\Jenkins\\1 - Introduction\\1 - Course Introduction 0235.en.vtt.part'
2024-03-15 18:36:27,233 - ERROR - Access denied while downloading video or audio file from link https://kodekloud.com/topic/course-introduction-16/
2024-03-15 18:36:29,036 - INFO - Writing video file... KodeKloud\Jenkins\1 - Introduction\2 - Application Details 0144...
2024-03-15 18:36:29,037 - INFO - Parsing url: https://kodekloud.com/topic/application-details/
[generic] Extracting URL: https://kodekloud.com/topic/application-details/
[generic] application-details: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] application-details: Extracting information
[vimeo] Extracting URL: https://player.vimeo.com/video/677999801?h=550365e00a&dnt=1&app_id=122963&controls=1&autoplay=1&m...ion-details%2F%22%7D
[vimeo] 677999801: Downloading webpage
ERROR: [vimeo] 677999801: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: Too Many Requests>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-03-15 18:36:30,721 - ERROR - Access denied while downloading video or audio file from link https://kodekloud.com/topic/application-details/
2024-03-15 18:36:31,931 - INFO - Writing video file... KodeKloud\Jenkins\1 - Introduction\3 - Working with the Application 0502...
2024-03-15 18:36:31,932 - INFO - Parsing url: https://kodekloud.com/topic/working-with-the-application/
[generic] Extracting URL: https://kodekloud.com/topic/working-with-the-application/
[generic] working-with-the-application: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] working-with-the-application: Extracting information
[vimeo] Extracting URL: https://player.vimeo.com/video/682397756?h=5ecbd5cbac&dnt=1&app_id=122963&controls=1&autoplay=1&m...application%2F%22%7D
[vimeo] 682397756: Downloading webpage
[vimeo] 682397756: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 682397756: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 682397756: Downloading fastly_skyfire m3u8 information
[vimeo] 682397756: Downloading fastly_skyfire m3u8 information
[vimeo] 682397756: Downloading akfire_interconnect_quic MPD information
[vimeo] 682397756: Downloading akfire_interconnect_quic MPD information
[vimeo] 682397756: Downloading fastly_skyfire MPD information
[vimeo] 682397756: Downloading fastly_skyfire MPD information
[info] 682397756: Downloading subtitles: en
[info] 682397756: Downloading 1 format(s): dash-fastly_skyfire_sep-video-52fea8ef+dash-fastly_skyfire_sep-audio-102d341f
[info] Writing video subtitles to: KodeKloud\Jenkins\1 - Introduction\3 - Working with the Application 0502.en.vtt
[download] Unable to open file: [Errno 13] Permission denied: 'KodeKloud\\Jenkins\\1 - Introduction\\3 - Working with the Application 0502.en.vtt.part'. Retrying (1/3)...
[download] Unable to open file: [Errno 13] Permission denied: 'KodeKloud\\Jenkins\\1 - Introduction\\3 - Working with the Application 0502.en.vtt.part'. Retrying (2/3)...
[download] Unable to open file: [Errno 13] Permission denied: 'KodeKloud\\Jenkins\\1 - Introduction\\3 - Working with the Application 0502.en.vtt.part'. Retrying (3/3)...
ERROR: unable to open for writing: [Errno 13] Permission denied: 'KodeKloud\\Jenkins\\1 - Introduction\\3 - Working with the Application 0502.en.vtt.part'
ERROR: Unable to download video subtitles for 'en': ERROR: unable to open for writing: [Errno 13] Permission denied: 'KodeKloud\\Jenkins\\1 - Introduction\\3 - Working with the Application 0502.en.vtt.part'
2024-03-15 18:36:39,010 - ERROR - Access denied while downloading video or audio file from link https://kodekloud.com/topic/working-with-the-application/
2024-03-15 18:36:40,487 - INFO - Writing resource file... KodeKloud\Jenkins\1 - Introduction\5 - Course Resources...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\vasan\AppData\Local\Programs\Python\Python312\Scripts\kodekloud.exe\__main__.py", line 7, in <module>
  File "C:\Users\vasan\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vasan\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\vasan\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vasan\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vasan\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vasan\AppData\Local\Programs\Python\Python312\Lib\site-packages\kodekloud_downloader\cli.py", line 50, in dl
    download_course(
  File "C:\Users\vasan\AppData\Local\Programs\Python\Python312\Lib\site-packages\kodekloud_downloader\main.py", line 58, in download_course
    download_resource_lesson(lesson, file_path, cookie)
  File "C:\Users\vasan\AppData\Local\Programs\Python\Python312\Lib\site-packages\kodekloud_downloader\main.py", line 131, in download_resource_lesson
    file_path.with_suffix(".md").write_text(markdownify.markdownify(content.prettify()), encoding="utf-8")
  File "C:\Users\vasan\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1047, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vasan\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'KodeKloud\\Jenkins\\1 - Introduction\\5 - Course Resources.md'
PS C:\WINDOWS\system32> kodekloud dl --help
Usage: kodekloud dl [OPTIONS] [COURSE_URL]

**Comment by debakarr** [comment]
Closing stale issues.
Please raise a new issue if you still see the problem :)
