### ISSUE TITLE
KodeKloudQuiz URL

### ISSUE THREAD

**Issue by Matkach** [debakarr/kodekloud-downloader#42]
I just tried this dl-quiz but it returns:
> kodekloud dl-quiz -o KodeKloudQuiz
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\kodekloud.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Python310\lib\site-packages\kodekloud_downloader\cli.py", line 101, in dl_quiz
    download_quiz(output_dir, sep)
  File "C:\Python310\lib\site-packages\kodekloud_downloader\main.py", line 27, in download_quiz
    response.raise_for_status()
  File "C:\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mcq-backend-main.kodekloud.com/quizzes

It seems that the URL has changed. By any chance you know the new URL?
Thanks in advance!

**Comment by imraj1997** [comment]
Same for me as well. Could you please update the new url?

**Comment by varunpalekar** [comment]
Same for me

**Comment by debakarr** [comment]
I am kind of busy with other work. But let me check on this.

**Comment by debakarr** [comment]
This should be fixed in the latest version: `pip install -U kodekloud-downloader`

**Comment by Matkach** [comment]
Thank you!
