### ISSUE TITLE
unable to download

### ISSUE THREAD

**Issue by Bharath509** [debakarr/kodekloud-downloader#47]
Getting this error while downloading

Traceback (most recent call last):
  File "/opt/homebrew/bin/kodekloud", line 8, in <module>
    sys.exit(kodekloud())
             ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/kodekloud_downloader/cli.py", line 65, in dl
    download_course(
  File "/opt/homebrew/lib/python3.11/site-packages/kodekloud_downloader/main.py", line 99, in download_course
    course_name = course_name_tag.text.strip()
                  ^^^^^^^^^^^^^^^^^^^^

Installed ffmpeg and ran the command kodekloud dl -q 1080p -o ./ -c ~/Downloads/learn.kodekloud.com_cookies.txt

python version:
Python 3.12.4

**Comment by ArturiaPendragon** [comment]
Same for me.

**Comment by jonbk** [comment]
same

**Comment by highrascal9098** [comment]
Is it resolved???

**Comment by CarlosJoseChaconChavarria** [comment]
seems like not working and next week is free
