### ISSUE TITLE
Not working for free week 2024

### ISSUE THREAD

**Issue by rakeshkhot5** [debakarr/kodekloud-downloader#51]
Not working for free week 2024. Below is the issue.

Traceback (most recent call last):
  File "/home/spring/.local/bin/kodekloud", line 8, in <module>
    sys.exit(kodekloud())
  File "/home/spring/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/spring/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/spring/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/spring/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/spring/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/spring/.local/lib/python3.10/site-packages/kodekloud_downloader/cli.py", line 65, in dl
    download_course(
  File "/home/spring/.local/lib/python3.10/site-packages/kodekloud_downloader/main.py", line 99, in download_course
    course_name = course_name_tag.text.strip()
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by debakarr** [comment]
hmm. Let me check. I had not looked into this for a long time now 😅. If everything goes well, expect things to fix by tonight (IST timezone).

**Comment by jonathan-nansen** [comment]
still doesn't work on my side
```
Traceback (most recent call last):
  File "/Users/jonathan/Library/Python/3.9/bin/kodekloud", line 8, in <module>
    sys.exit(kodekloud())
  File "/Users/jonathan/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jonathan/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/jonathan/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jonathan/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jonathan/Library/Python/3.9/lib/python/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jonathan/Library/Python/3.9/lib/python/site-packages/kodekloud_downloader/cli.py", line 65, in dl
    download_course(
  File "/Users/jonathan/Library/Python/3.9/lib/python/site-packages/kodekloud_downloader/main.py", line 98, in download_course
    course_name = course_name_tag.text.strip()
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by debakarr** [comment]
> still doesn't work on my side
> ```
> Traceback (most recent call last):
>   File "/Users/jonathan/Library/Python/3.9/bin/kodekloud", line 8, in <module>
>     sys.exit(kodekloud())
>   File "/Users/jonathan/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/jonathan/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/Users/jonathan/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Users/jonathan/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/jonathan/Library/Python/3.9/lib/python/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/Users/jonathan/Library/Python/3.9/lib/python/site-packages/kodekloud_downloader/cli.py", line 65, in dl
>     download_course(
>   File "/Users/jonathan/Library/Python/3.9/lib/python/site-packages/kodekloud_downloader/main.py", line 98, in download_course
>     course_name = course_name_tag.text.strip()
> AttributeError: 'NoneType' object has no attribute 'text'
> ```

Try to update the package to the latest version or install from the main branch.
