### ISSUE TITLE
facing an Error

### ISSUE THREAD

**Issue by BNareshSolanki** [debakarr/kodekloud-downloader#59]
Traceback (most recent call last):

File "/home/naresh/local/lib/python3.12/site-packages/kodekloud_downloader/helpers.py", line 164, in parse token with open(cookiefile, "r") as for

FileNotFoundError! (Errno 2) No such file or directory: 'learn.kodekloud.com cookies.txt'

During handling of the above exception, another exception occurredi

Traceback (most recent call last):

File "/home/naresh/.local/bin/kodekloud", line 8, in <module>

sys.exit(kodekloud())

File "/usr/lib/python3/dist-packages/click/core.py", line 1157, incall return self.main(*args, **kwargs)

File "/usr/lib/python3/dist-packages/click/core.py", line 1978, in main rv self.invoke(ctx)

File "/usr/lib/python3/dist-packages/click/core.py", line 1688, in invoke return process_result(sub_ctx.command, Invoke(sub ctx))

File "/usr/lib/python3/dist-packages/click/core.py", line 1434, in invoke return ctx, Invoke(self.callback, ctx.params)

File "/usr/lib/python3/dist-packages/click/core.py", line 783, in invoke

return callback(*args, **kwargs)

File "/home/naresh/.local/lib/python3.12/site-packages/kodekloud_downloader/clt.py", line 78,

?

in dl

File "/home/naresh/.local/lib/python3.12/site-packages/kodekloud_downloader/main.py", line 119, in download course

session token parse token(cookie)

File "/home/naresh/.local/lib/python3.12/site-packages/kodekloud_downloader/helpers.py", line 171, in parse token raise FileNotFoundError (f"The file (cookiefile) does not exist.") FileNotFoundError: The file learn.kodekloud.com_cookies.txt does not exist.

**Comment by waligi** [comment]
`f"The file (cookiefile) does not exist.") FileNotFoundError: The file learn.kodekloud.com_cookies.txt does not exist.`

I believe this means you need to download the cookie file. check the instructions. it shows how to download it.
