### ISSUE TITLE
Couldn't download Pro Courses

### ISSUE THREAD

**Issue by imraj1997** [debakarr/kodekloud-downloader#60]
Hello,

First of all, thank you so much for this tool. This is a life saver. ❤️

Now coming to the issue. When I tried to download one of the pro courses ( 3   | Amazon Elastic Compute Cloud (EC2)                                                   | Pro      | AWS, Cloud, DevOps, Infrastructure as Code (IaC)  )

I get the below error.

Enter the courses you want to select (Multiple courses can be passes using this format 1,6-9,10-11): 3
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\usraj\AppData\Local\Programs\Python\Python312\Scripts\kodekloud.exe\__main__.py", line 7, in <module>
  File "C:\Users\usraj\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usraj\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\usraj\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usraj\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usraj\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usraj\AppData\Local\Programs\Python\Python312\Lib\site-packages\kodekloud_downloader\cli.py", line 69, in dl
    download_course(
  File "C:\Users\usraj\AppData\Local\Programs\Python\Python312\Lib\site-packages\kodekloud_downloader\main.py", line 145, in download_course
    response.raise_for_status()
  File "C:\Users\usraj\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://learn-api.kodekloud.com/api/lessons/b3cb616c-f0bb-466a-a176-dabfdeef8616?course_id=ab9df08d-7087-491b-a398-b49f84de50b9

Any help on this would be highly appreciated.

**Comment by debakarr** [comment]
Do you have access to those courses? I mean do you have Pro plan.
AFAIK pro plan are not accessible even in Free Week.

Sadly I don't have the Pro plan so I couldn't try out the downloader for those :(

**Comment by Tisona** [comment]
Pro courses are not free, even during the free week.
This is because Kodecloud has to provision AWS resources for the labs.

**Comment by debakarr** [comment]
As mentioned, pro course can only be downloaded in case you have access.
