### ISSUE TITLE
Couldn't download some courses

### ISSUE THREAD

**Issue by WillyManson** [debakarr/kodekloud-downloader#61]
Hello,
First of all, thank you so much for this tool.
I get the below error with 96, 91, 88, 67, 60(for example):

[download] Destination: e:\kodekloud\KodeKloud\Advanced Bash Scripting\12 - sed\5 - Substitute.fhls-fastly_skyfire-audio-high-Original.mp4
[download] 100% of   13.53MiB in 00:00:02 at 5.85MiB/s
[Merger] Merging formats into "e:\kodekloud\KodeKloud\Advanced Bash Scripting\12 - sed\5 - Substitute.mkv"
Deleting original file e:\kodekloud\KodeKloud\Advanced Bash Scripting\12 - sed\5 - Substitute.fhls-fastly_skyfire-audio-high-Original.mp4 (pass -k to keep)
Deleting original file e:\kodekloud\KodeKloud\Advanced Bash Scripting\12 - sed\5 - Substitute.fhls-fastly_skyfire-478.mp4 (pass -k to keep)
Traceback (most recent call last):
  File "C:\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\python\Scripts\kodekloud.exe\__main__.py", line 7, in <module>
  File "C:\python\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\python\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\python\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\python\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\python\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\python\lib\site-packages\kodekloud_downloader\cli.py", line 69, in dl
    download_course(
  File "C:\python\lib\site-packages\kodekloud_downloader\main.py", line 126, in download_course
    fetch_course_detail(course.slug) if isinstance(course, Course) else course
  File "C:\python\lib\site-packages\kodekloud_downloader\models\helper.py", line 36, in fetch_course_detail
    return CourseDetail(**data)
  File "C:\python\lib\site-packages\pydantic\main.py", line 209, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for CourseDetail
excerpt
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type

[download] Destination: e:\kodekloud\KodeKloud\GitOps with FluxCD\8 - Monitoring  User Interface\5 - DEMO  Flux User Interface.en.vtt
[download] 100% of   17.28KiB in 00:00:00 at 40.20KiB/s
[download] e:\kodekloud\KodeKloud\GitOps with FluxCD\8 - Monitoring  User Interface\5 - DEMO  Flux User Interface.mkv has already been downloaded
Traceback (most recent call last):
  File "C:\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\python\Scripts\kodekloud.exe\__main__.py", line 7, in <module>
  File "C:\python\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\python\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\python\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\python\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\python\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\python\lib\site-packages\kodekloud_downloader\cli.py", line 69, in dl
    download_course(
  File "C:\python\lib\site-packages\kodekloud_downloader\main.py", line 126, in download_course
    fetch_course_detail(course.slug) if isinstance(course, Course) else course
  File "C:\python\lib\site-packages\kodekloud_downloader\models\helper.py", line 36, in fetch_course_detail
    return CourseDetail(**data)
  File "C:\python\lib\site-packages\pydantic\main.py", line 209, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for CourseDetail
excerpt
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type

**Comment by WillyManson** [comment]
Enter the courses you want to select (Multiple courses can be passes using this format 1,6-9,10-11): 91
Traceback (most recent call last):
  File "C:\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\python\Scripts\kodekloud.exe\__main__.py", line 7, in <module>
  File "C:\python\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\python\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\python\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\python\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\python\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\python\lib\site-packages\kodekloud_downloader\cli.py", line 69, in dl
    download_course(
  File "C:\python\lib\site-packages\kodekloud_downloader\main.py", line 126, in download_course
    fetch_course_detail(course.slug) if isinstance(course, Course) else course
  File "C:\python\lib\site-packages\kodekloud_downloader\models\helper.py", line 36, in fetch_course_detail
    return CourseDetail(**data)
  File "C:\python\lib\site-packages\pydantic\main.py", line 209, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for CourseDetail
excerpt
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type

**Comment by manibalajic** [comment]
Maybe thier API rate limiting , i also face the same problem.

**Comment by debakarr** [comment]
This is duplicate of #55 which is fixed in #57.
Try the changes in main branch. I still haven't moved the tag:

```console
pip install -U git+https://github.com/debakarr/kodekloud-downloader.git@main
```

**Comment by WillyManson** [comment]
It is on 8a86334 commit:

PS D:\downloads> pip install -U git+https://github.com/debakarr/kodekloud-downloader.git@main
Collecting git+https://github.com/debakarr/kodekloud-downloader.git@main
  Cloning https://github.com/debakarr/kodekloud-downloader.git (to revision main) to c:\users\kc\appdata\local\temp\pip-req-build-0302v7va
  Running command git clone --filter=blob:none --quiet https://github.com/debakarr/kodekloud-downloader.git 'C:\Users\kc\AppData\Local\Temp\pip-req-build-0302v7va'
  Resolved https://github.com/debakarr/kodekloud-downloader.git to commit 8a8633420a727777666023477c99a603f1fe59c9
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
...
Enter the courses you want to select (Multiple courses can be passes using this format 1,6-9,10-11): 90
Traceback (most recent call last):
  File "C:\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\python\Scripts\kodekloud.exe\__main__.py", line 7, in <module>
  File "C:\python\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\python\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\python\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\python\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\python\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\python\lib\site-packages\kodekloud_downloader\cli.py", line 69, in dl
    download_course(
  File "C:\python\lib\site-packages\kodekloud_downloader\main.py", line 126, in download_course
    fetch_course_detail(course.slug) if isinstance(course, Course) else course
  File "C:\python\lib\site-packages\kodekloud_downloader\models\helper.py", line 36, in fetch_course_detail
    return CourseDetail(**data)
  File "C:\python\lib\site-packages\pydantic\main.py", line 209, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for CourseDetail
excerpt
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type

**Comment by manibalajic** [comment]
Yes , i still face the same after update with the commit.
