### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kirillmasanov** [debakarr/kodekloud-downloader#62]
```
Enter the courses you want to select (Multiple courses can be passes using this format 1,6-9,10-11): 22
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\kodekloud.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "c:\python39\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "c:\python39\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python39\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python39\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "c:\python39\lib\site-packages\kodekloud_downloader\cli.py", line 65, in dl
    download_course(
  File "c:\python39\lib\site-packages\kodekloud_downloader\main.py", line 98, in download_course
    course_name = course_name_tag.text.strip()
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by debakarr** [comment]
Most probably you don't have the latest changes.

Try:

```console
pip install -U git+https://github.com/debakarr/kodekloud-downloader.git --force-reinstall
```
