### ISSUE TITLE
Issue when trying to download `Ansible Advanced Course`

### ISSUE THREAD

**Issue by abdoaboganima** [debakarr/kodekloud-downloader#64]
While choosing the 90th course, the following error appears:
```
Traceback (most recent call last):
  File "/home/abdo/.local/bin/kodekloud", line 8, in <module>
    sys.exit(kodekloud())
  File "/home/abdo/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/abdo/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/abdo/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/abdo/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/abdo/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/abdo/.local/lib/python3.10/site-packages/kodekloud_downloader/cli.py", line 69, in dl
    download_course(
  File "/home/abdo/.local/lib/python3.10/site-packages/kodekloud_downloader/main.py", line 126, in download_course
    fetch_course_detail(course.slug) if isinstance(course, Course) else course
  File "/home/abdo/.local/lib/python3.10/site-packages/kodekloud_downloader/models/helper.py", line 36, in fetch_course_detail
    return CourseDetail(**data)
  File "/home/abdo/.local/lib/python3.10/site-packages/pydantic/main.py", line 209, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for CourseDetail
excerpt
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type
```
and this errors happens only for the `Ansible Advanced Course`. 
**Note**: _I already have enrolled to that course_

**Comment by ravikyada** [comment]
I'm also facing the same issue.

**Comment by debakarr** [comment]
I tried downloading it today and didn't see any issue. You can retry.
