### ISSUE TITLE
Quiz download fails possibly due to special character

### ISSUE THREAD

**Issue by ivan-n20** [debakarr/kodekloud-downloader#65]
Using latest pull and ran the command
`kodekloud dl-quiz -o KodeKloudQuiz --sep`

```
Quiz file written in KodeKloudQuiz\mockexam2-az900.md
Fetching Quiz 327 - Are you already a great communicator
Quiz file written in KodeKloudQuiz\Are you already a great communicator.md
Fetching Quiz 328 - Are you already a capable leader and influencer
Quiz file written in KodeKloudQuiz\Are you already a capable leader and influencer.md
Fetching Quiz 329 - Are you already a collaborator?
Traceback (most recent call last):
  File "C:\Users\user111\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user111\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user111\AppData\Local\Programs\Python\Python310\Scripts\kodekloud.exe\_main_.py", line 7, in <module>
  File "C:\Users\user111\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1157, in _call_
    return self.main(*args, **kwargs)
  File "C:\Users\user111\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\user111\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\user111\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\user111\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\user111\AppData\Local\Programs\Python\Python310\lib\site-packages\kodekloud_downloader\cli.py", line 106, in dl_quiz
    download_quiz(output_dir, sep)
  File "C:\Users\user111\AppData\Local\Programs\Python\Python310\lib\site-packages\kodekloud_downloader\main.py", line 73, in download_quiz
    with open(output_file, "w", encoding="utf-8") as f:
OSError: [Errno 22] Invalid argument: 'KodeKloudQuiz\\Are you already a collaborator?.md'
```

Executed on cmd prompt on Windows 10/11

**Comment by amitfegade121** [comment]
This issue occurred because of special character ? in quiz file name. I have fixed this issue by making chanes in below line.

output_file = Path(output_dir) / f"{quiz_name.replace('/', '').replace('?','')}.md"

line no. 70 of C:\Users\user111\AppData\Local\Programs\Python\Python310\lib\site-packages\kodekloud_downloader\main.py file.

**Comment by debakarr** [comment]
Fixed by PR #110 — quiz filenames are now sanitized to remove Windows-invalid characters.
