### ISSUE TITLE
Getting  Error (alidation error for ApiResponse courses)

### ISSUE THREAD

**Issue by shahidge4** [debakarr/kodekloud-downloader#73]
kodekloud dl -o . -c cookies.txt
Traceback (most recent call last):
  File "/usr/local/bin/kodekloud", line 8, in <module>
    sys.exit(kodekloud())
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/kodekloud_downloader/cli.py", line 66, in dl
    courses = collect_all_courses()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/kodekloud_downloader/models/helper.py", line 22, in collect_all_courses
    api_response = fetch_courses(page, limit)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/kodekloud_downloader/models/helper.py", line 14, in fetch_courses
    return ApiResponse(**data)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for ApiResponse
courses.23.thumbnail_url
  URL input should be a string or URL [type=url_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/url_type

**Comment by debakarr** [comment]
Hi! 👋 This schema validation error should be fixed by PR #90 (pending review) which removes the \community_support\ field from the model since it no longer exists in the API. Thanks for reporting!
